### ISSUE TITLE
General comments on module

### ISSUE THREAD

**Issue by mmcdermott** [payalchandak/EveryQuery#6]
Should this be a module level metric? https://github.com/payalchandak/EveryQuery/blob/ed5a70de5d6054d1502d7181291fb0c6b0647f3b/src/models/everyquery.py#L36
In fact, I don't think this will be right, as this is batch level, when you want dataset level, no?

Should have a parameter for dropout:
https://github.com/payalchandak/EveryQuery/blob/ed5a70de5d6054d1502d7181291fb0c6b0647f3b/src/models/everyquery.py#L22

Why bother renaming these?
https://github.com/payalchandak/EveryQuery/blob/main/src/models/everyquery.py#L4

Why have this split?
https://github.com/payalchandak/EveryQuery/blob/main/src/models/everyquery.py#L92

**Comment by payalchandak** [comment]
Fixed the metric

Will link dropout to existing backbone dropout param 

Got rid of those entirely 
`from meds_torch.models import BACKBONE_EMBEDDINGS_KEY as EMBED, MODEL_BATCH_LOSS_KEY as LOSS`

This is because you can do "predict_step" the lightning module and may want to return the batch or embeddings etc
```
        if split in ['train','val','test']: 
            return batch[LOSS]
        else:
            return batch
```
